apiVersion: v1
kind: Service
metadata:
  name: postgres-new
  namespace: kong
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres-new
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-new
  namespace: kong
spec:
  serviceName: "postgres-new"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-new
  template:
    metadata:
      labels:
        app: postgres-new
    spec:
      containers:
      - name: postgres
        image: postgres:13.9
        env:
        - name: POSTGRES_USER
          value: kong
        - name: POSTGRES_PASSWORD
          value: kong
        - name: POSTGRES_DB
          value: kong
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
